{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "troller.serviceAccountName" . }}
  namespace: {{ include "troller.name" . }}
  labels:
{{ include "troller.labels" . | indent 4 }}
{{- end -}}
